# configuration for https://ohi-science.nceas.ucsb.edu/ltu
study_area:       Lithuania
git_owner:        OHI-Science
git_repo:         ltu
git_slug:         OHI-Science/ltu
git_url:          https://github.com/OHI-Science/ltu
app_url:          http://ohi-science.nceas.ucsb.edu/ltu
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-03-23
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: 4430cb9fbd06adcb7bb7803f4542714f2fd01b19

tabs_hide:        
- Calculate
- Report

